import "./globals.css";
import { Inter } from "next/font/google"



export const metadata = {
  title: "Gestão esportiva ADM SENAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
