import "./globals.css";
import { Inter } from "next/font/google"
import AuthProvider from "../contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] })


export const metadata = {
  title: "Gestão esportiva ADM SENAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
